spring:
  application:
    name: mockup
  datasource:
    url: jdbc:postgresql://localhost:5432/mockup
    username: postgres
    password: root

server:
  port: 8282
  servlet:
    context-path: /mockup
